import os

ROOM_LIST = ["Dinning Room", "Bedroom", "Bathroom"]
DINNING_INTERACTIONS = ["Sink", "Television", "Couch"]
BEDROOM_INTERACTIONS = ["Bed", "Computer", "Dresser"]
BATHROOM_INTERACTIONS = ["Sink", "Bathtub", "Toliet"]

SCREEN_WIDTH = 1000
SCREEN_HEIGHT = 650
SCREEN_TITLE = "Python Ghost Hunter"

#TILE_SCALING = 0.5
#CHARACTER_SCALING = TILE_SCALING * 2
#PLAYER_MOVEMENT_SPEED = 5
#GHOST_MOVEMENT_SPEED = 5

LEFT_VIEWPORT_MARGIN = 200
RIGHT_VIEWPORT_MARGIN = 200
BOTTOM_VIEWPORT_MARGIN = 150
TOP_VIEWPORT_MARGIN = 100

PLAYER_START_X = 2
PLAYER_START_Y = 1
